name: Build

on:
  push:
    branches:
      - master
      - development
  pull_request:
    branches:
      - master
      - development

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: stable

      - name: Create .env file
        run: |
          echo "SPOTIFY_CLIENT=${{ secrets.SPOTIFY_CLIENT }}" >> ./frontend/assets/.env
          echo "SPOTIFY_CLIENT_SECRET=${{ secrets.SPOTIFY_CLIENT_SECRET }}" >> ./frontend/assets/.env
          echo "REDIRECT_URI=${{ secrets.REDIRECT_URI }}" >> ./frontend/assets/.env
          echo "SPOTIFY_CLIENT_ID=${{ secrets.SPOTIFY_CLIENT_ID }}" >> ./frontend/assets/.env
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> ./frontend/assets/.env
          
      - run: flutter build apk --debug
        working-directory: ./frontend
 
