name: Flutter Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'latest'

      - name: Install dependencies
        run: flutter pub get
        working-directory: ./frontend  # Specify the working directory

      - name: Run Linter
        run: flutter analyze
        working-directory: ./frontend  # Specify the working directory
