name: Lint

on:
  push:
    branches:
      - master
      - development
  pull_request:
    branches:
      - master
      - development

jobs:
  linter:
        runs-on: ubuntu-latest
    
        steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-java@v1
            with:
              java-version: "12.x"
          - name: Install Flutter
            run: git clone https://github.com/flutter/flutter.git -b stable
          - name: Run Flutter doctor
            run: ./flutter/bin/flutter doctor
          - name: Run Linter
            run: ./flutter/bin/flutter analyze .
            
    

 
