name: Flutter Linting

on:
  push:
    branches:
      - master
      - development
  pull_request:
    branches:
      - master
      - development

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get
        working-directory: ./frontend  # Specify the working directory

      - name: Run Linter
        run: flutter analyze
        working-directory: ./frontend  # Specify the working directory

